title = "2. Ilmenauer Open 2025"
baseURL = "https://open.ilmenauer-schachverein.de"
defaultContentLanguage = "de"
enableGitInfo = true

googleAnalytics = "G-BFH7CVL2EJ"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra"
  [[module.imports]]
    path = "github.com/gethinode/mod-flexsearch"
  [[module.imports]]
    path = "github.com/mfg92/hugo-shortcode-gallery"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    noClasses = false

[languages]
  [languages.de]
    languageName = "German"
    weight = 1
    title = "2. Ilmenauer Open 2025"
    contentDir = "content/de"

[menu]
  [[menu.main]]
    name = "Chess-Results"
    url = "https://s3.chess-results.com/tnr1056124.aspx?lan=0&SNode=S0"
    weight = 1
  [[menu.main]]
    name = "Ausschreibung"
    pageRef = "/2025/ausschreibung"
    weight = 1
  [[menu.main]]
    name = "Runden"
    pageRef = "/2025/open/runde"
    weight = 1
  [[menu.main]]
    name = "Startrangliste"
    pageRef = "/2025/startrangliste"
    weight = 1
  [[menu.main]]
    name = "Ilmenauer Schachverein ↗"
    url = "https://ilmenauer-schachverein.de"
    weight = 4
  [[menu.main]]
    name = "Search"
    weight = 5
    [menu.main.params]
      type = "search"
  [[menu.main]]
    name = "GitHub"
    weight = 6
    url = "https://github.com/IlmenauerSchachverein/IlmenauerOpen"
    [menu.main.params]
      icon = "github"
  [[menu.main]]
    name = "Instagram"
    weight = 7
    url = "https://instagram.com/ilmenauer_schachverein"
    [menu.main.params]
      icon = "instagram"

[params]
  disableToc = true

  [params.navbar]
    displayTitle = true
    displayLogo = true

  [params.theme]
    default = "system"

  [params.footer]
    displayCopyright = true
    displayPoweredBy = true

  [params.editURL]
    enable = false
    base = ""

  [params.page]
    width = "full"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"  
